### ISSUE TITLE
ImportError: cannot import name 'encodestring' from 'base64'

### ISSUE THREAD

**Issue by homosapien-lcy** [enthought/chaco#887] opened 2023-04-11 08:28 UTC
**Problem Description**
ImportError: cannot import name 'encodestring' from 'base64' when running chaco/examples/demo/advanced/javascript_hover_tools.py

**Reproduction Steps:**

```python
python chaco/examples/demo/advanced/javascript_hover_tools.py
```

**OS, Python version:** 
[MacOS, python3.11]

Packages:
Package             Version
------------------- --------
altgraph            0.17.2
autopep8            2.0.1
boto3               1.26.50
botocore            1.29.50
camelot-py          0.10.1
cffi                1.15.1
chardet             5.1.0
charset-normalizer  3.0.1
click               8.1.3
contourpy           1.0.7
cryptography        39.0.0
cycler              0.11.0
Cython              0.29.33
distro              1.8.0
et-xmlfile          1.1.0
fonttools           4.39.0
future              0.18.2
importlib-metadata  6.3.0
importlib-resources 5.12.0
install             1.3.5
isort               5.12.0
jmespath            1.0.1
kiwisolver          1.4.4
macholib            1.15.2
matplotlib          3.7.1
numpy               1.24.1
opencv-python       4.7.0.68
openpyxl            3.0.10
packaging           23.0
pandas              1.5.2
pdfminer.six        20221105
Pillow              9.3.0
pip                 21.2.4
pycodestyle         2.10.0
pycparser           2.21
pyface              8.0.0
PyMuPDF             1.21.1
pyparsing           3.0.9
PyPDF2              2.12.1
PyQt5               5.15.9
PyQt5-Qt5           5.15.2
PyQt5-sip           12.11.1
PySide6             6.4.2
PySide6-Addons      6.4.2
PySide6-Essentials  6.4.2
python-dateutil     2.8.2
pytz                2022.7.1
s3transfer          0.6.0
scipy               1.10.1
setuptools          58.0.4
shiboken6           6.4.2
six                 1.15.0
tabula-py           2.6.0
tabulate            0.9.0
textract-trp        0.1.3
tomli               2.0.1
traits              6.4.1
traitsui            7.4.3
typing_extensions   4.4.0
urllib3             1.26.14
vtk                 9.2.6
wheel               0.37.0
zipp                3.15.0

**Comment by dpinte** [comment] 2023-04-11 09:57
Closing as a duplicate of #868

**Closed by dpinte** 2023-04-11 09:57 UTC
