### ISSUE TITLE
Incomplete sections in docs

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#313] opened 2016-10-06 07:33 UTC
- [ ] missing information from [tools and overlays](http://docs.enthought.com/chaco/user_manual/tools.html)
- [ ] missing information in [common usages](http://docs.enthought.com/chaco/user_manual/common_patterns.html)

**Comment by achabotl** [comment] 2019-07-14 21:01
Duplicate of #161.

**Closed by achabotl** 2019-07-14 21:01 UTC
Labels: Good First Issue, documentation, duplicate
