### ISSUE TITLE
Demo basic/tabbed_plot.py

### ISSUE THREAD

**Issue by ku-ya** [enthought/chaco#418] opened 2018-07-14 19:41 UTC
**Problem Description**
tan tab plot not showing
**Reproduction Steps:**
Run tabbed_plot.py

**Expected behavior:**
tan tab is not plotting

**OS, Python version:** 
OSX Python2.7

splits from #385

**Comment by midhun-pm** [comment] 2019-12-26 18:26
Unable to reproduce on Linux. Need to test on OSX
I'm guessing this refers to the file : examples/demo/basic/tabbed_plots.py , can't find tabbed_plot.py
Tried out with python2.7, Qt back-end.

Plots are displayed on both tabs.

**Comment by rahulporuri** [comment] 2021-03-24 09:05
closing as i can't reproduce this at the moment on windows.

**Closed by rahulporuri** 2021-03-24 09:05 UTC
Labels: component: demos
