### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by mckatzenelson** [enthought/chaco#271] opened 2015-05-05 00:19 UTC
platform  Fedora 21

contents of pip.log:

Requirement already satisfied (use --upgrade to upgrade): chaco in /usr/lib/python2.7/site-packages/chaco-4.5.0-py2.7-linux-x86_64.egg
Downloading/unpacking enable (from chaco)
  Getting page https://pypi.python.org/simple/enable/
  URLs to search for versions for enable (from chaco):
  * https://pypi.python.org/simple/enable/
  Analyzing links from page https://pypi.python.org/simple/enable/
    Found link https://pypi.python.org/packages/source/e/enable/enable-4.4.0.tar.gz#md5=7941d3ae87c0823a86fc9c64fa0bc213 (from https://pypi.python.org/simple/enable/), version: 4.4.0
    Found link https://pypi.python.org/packages/source/e/enable/enable-4.4.1.tar.gz#md5=1a21c91fc7db801c3b7b26d9014e85e4 (from https://pypi.python.org/simple/enable/), version: 4.4.1
    Found link https://pypi.python.org/packages/source/e/enable/enable-4.5.0.zip#md5=7f8b6161840f6741962f29f406bca633 (from https://pypi.python.org/simple/enable/), version: 4.5.0
    Found link https://pypi.python.org/packages/source/e/enable/enable-4.5.1.tar.gz#md5=bfc6d30198265deee9dedaebebdf21b9 (from https://pypi.python.org/simple/enable/), version: 4.5.1
    Found link https://pypi.python.org/packages/source/e/enable/enable-4.5.1.zip#md5=01d8a986871bd13cbea5231a4c523c78 (from https://pypi.python.org/simple/enable/), version: 4.5.1
    Skipping link http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2 (from https://pypi.python.org/simple/enable/); wrong project name (not enable)
    Skipping link http://code.enthought.com/projects/enable (from https://pypi.python.org/simple/enable/); not a file
    Skipping link http://github.enthought.com/enable (from https://pypi.python.org/simple/enable/); not a file
    Skipping link http://www.cython.org (from https://pypi.python.org/simple/enable/); not a file
    Skipping http://www.enthought.com/repo/ets/enable-4.0.0.tar.gz (from https://pypi.python.org/simple/enable/) because it is externally hosted.
    Skipping http://www.enthought.com/repo/ets/enable-4.1.0.tar.gz (from https://pypi.python.org/simple/enable/) because it is externally hosted.
    Skipping http://www.enthought.com/repo/ets/enable-4.2.0.tar.gz (from https://pypi.python.org/simple/enable/) because it is externally hosted.
    Skipping http://www.enthought.com/repo/ets/enable-4.3.0.tar.gz (from https://pypi.python.org/simple/enable/) because it is externally hosted.
    Skipping http://www.enthought.com/repo/ets/enable-4.4.0.tar.gz (from https://pypi.python.org/simple/enable/) because it is externally hosted.
    Skipping http://www.enthought.com/repo/ets/enable-4.4.1.tar.gz (from https://pypi.python.org/simple/enable/) because it is externally hosted.
    Skipping link http://www.pythonware.com/products/pil (from https://pypi.python.org/simple/enable/); not a file
    Skipping link http://www.reportlab.org/rl_toolkit.html/ (from https://pypi.python.org/simple/enable/); unknown archive format: .html
    Skipping link http://www.swig.org/ (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://bitbucket.org/pyglet/pyglet/get/pyglet-1.1.4.zip (from https://pypi.python.org/simple/enable/); wrong project name (not enable)
    Skipping link https://coveralls.io/r/enthought/enable (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://github.com/enthought/enable/ (from https://pypi.python.org/simple/enable/); not a file
    Could not parse version from link: https://github.com/enthought/enable/archive/4.5.0.tar.gz (from https://pypi.python.org/simple/enable/)
    Skipping link https://github.com/enthought/enable/archive/4.5.0.tar.gz (from https://pypi.python.org/simple/enable/); wrong project name (not enable)
    Could not parse version from link: https://github.com/enthought/enable/archive/4.5.1.tar.gz (from https://pypi.python.org/simple/enable/)
    Skipping link https://github.com/enthought/enable/archive/4.5.1.tar.gz (from https://pypi.python.org/simple/enable/); wrong project name (not enable)
    Skipping link https://pypi.python.org/pypi/PyQt4 (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/PySide (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/apptools/ (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/kiwisolver (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/pyface (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/pygarrayimage (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/pyparsing (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/setuptools (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/traits (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/traitsui (from https://pypi.python.org/simple/enable/); not a file
    Skipping link https://pypi.python.org/pypi/wxPython/2.8.11.0 (from https://pypi.python.org/simple/enable/); unknown archive format: .0
    Skipping link https://travis-ci.org/enthought/enable (from https://pypi.python.org/simple/enable/); not a file
  Using version 4.5.1 (newest of versions: 4.5.1, 4.5.1, 4.5.0, 4.4.1, 4.4.0)
  Downloading from URL https://pypi.python.org/packages/source/e/enable/enable-4.5.1.tar.gz#md5=bfc6d30198265deee9dedaebebdf21b9 (from https://pypi.python.org/simple/enable/)
  Running setup.py (path:/tmp/pip-build-kDREI5/enable/setup.py) egg_info for package enable
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/lib64/python2.7/site-packages/numpy/__init__.pyc/include/python2.7 is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/local/include/python2.7 is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path  is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11R6/lib64 is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11R6/lib is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11/lib64 is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11/lib is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11R6/include is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11/include is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    abort: there is no Mercurial repository here (.hg not found)
    could not resolve pattern in 'kiva': '*.txt'
    non-existing path in 'kiva/agg': 'tests'
    could not resolve pattern in 'kiva/agg': '*.txt'
    could not resolve pattern in 'kiva/agg': '*.bat'
    could not resolve pattern in 'kiva': 'fonttools/fontTools/*.txt'
    running egg_info
    running build_src
    build_src
    building library "freetype2_src" sources
    creating build
    creating build/src.linux-x86_64-2.7
      adding 'kiva/agg/freetype2/src/autofit/autofit.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftbase.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftsystem.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftinit.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftglyph.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftmm.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftbdf.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftbbox.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftdebug.c' to sources.
      adding 'kiva/agg/freetype2/src/base/ftxf86.c' to sources.
      adding 'kiva/agg/freetype2/src/base/fttype1.c' to sources.
      adding 'kiva/agg/freetype2/src/bdf/bdf.c' to sources.
      adding 'kiva/agg/freetype2/src/cff/cff.c' to sources.
      adding 'kiva/agg/freetype2/src/cid/type1cid.c' to sources.
      adding 'kiva/agg/freetype2/src/lzw/ftlzw.c' to sources.
      adding 'kiva/agg/freetype2/src/pcf/pcf.c' to sources.
      adding 'kiva/agg/freetype2/src/pfr/pfr.c' to sources.
      adding 'kiva/agg/freetype2/src/psaux/psaux.c' to sources.
      adding 'kiva/agg/freetype2/src/pshinter/pshinter.c' to sources.
      adding 'kiva/agg/freetype2/src/psnames/psnames.c' to sources.
      adding 'kiva/agg/freetype2/src/raster/raster.c' to sources.
      adding 'kiva/agg/freetype2/src/sfnt/sfnt.c' to sources.
      adding 'kiva/agg/freetype2/src/smooth/smooth.c' to sources.
      adding 'kiva/agg/freetype2/src/truetype/truetype.c' to sources.
      adding 'kiva/agg/freetype2/src/type1/type1.c' to sources.
      adding 'kiva/agg/freetype2/src/type42/type42.c' to sources.
      adding 'kiva/agg/freetype2/src/winfonts/winfnt.c' to sources.
      adding 'kiva/agg/freetype2/src/gzip/ftgzip.c' to sources.
    building library "agg24_src" sources
    building library "kiva_src" sources
    building extension "kiva.agg._agg" sources
    creating build/src.linux-x86_64-2.7/kiva
    creating build/src.linux-x86_64-2.7/kiva/agg
    swig++: kiva/agg/agg.i
    swig -python -c++ -Ikiva/agg/src -Ikiva/agg/agg-24/include -Ikiva/agg/agg-24/font_freetype -Ikiva/agg/freetype2/src/autofit -Ikiva/agg/freetype2/src/base -Ikiva/agg/freetype2/src/bdf -Ikiva/agg/freetype2/src/cache -Ikiva/agg/freetype2/src/cff -Ikiva/agg/freetype2/src/cid -Ikiva/agg/freetype2/src/gxvalid -Ikiva/agg/freetype2/src/gzip -Ikiva/agg/freetype2/src/lzw -Ikiva/agg/freetype2/src/otvalid -Ikiva/agg/freetype2/src/pcf -Ikiva/agg/freetype2/src/pfr -Ikiva/agg/freetype2/src/psaux -Ikiva/agg/freetype2/src/pshinter -Ikiva/agg/freetype2/src/psnames -Ikiva/agg/freetype2/src/raster -Ikiva/agg/freetype2/src/sfnt -Ikiva/agg/freetype2/src/smooth -Ikiva/agg/freetype2/src/tools -Ikiva/agg/freetype2/src/truetype -Ikiva/agg/freetype2/src/type1 -Ikiva/agg/freetype2/src/type42 -Ikiva/agg/freetype2/src/winfonts -Ikiva/agg/freetype2/src/gzip -Ikiva/agg/freetype2/include -Ikiva/agg/freetype2/src -I/usr/lib64/python2.7/site-packages/numpy/core/include -o build/src.linux-x86_64-2.7/kiva/agg/agg_wrap.cpp -outdir build/src.linux-x86_64-2.7/kiva/agg kiva/agg/agg.i
    kiva/agg/src/constants.i:51: Error: Unknown SWIG preprocessor directive: map (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:52: Error: Unknown SWIG preprocessor directive: marker (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:53: Error: Unknown SWIG preprocessor directive: marker (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:72: Error: Unknown SWIG preprocessor directive: Map (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:73: Error: Unknown SWIG preprocessor directive: pix (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:74: Error: Unknown SWIG preprocessor directive: pix (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:94: Error: Unknown SWIG preprocessor directive: Map (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:121: Error: Unknown SWIG preprocessor directive: Map (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:122: Error: Unknown SWIG preprocessor directive: interp (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/constants.i:123: Error: Unknown SWIG preprocessor directive: interp (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/rgba.i:85: Error: Unknown SWIG preprocessor directive: Use (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/affine_matrix.i:168: Error: Unknown SWIG preprocessor directive: AffineMatrix (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/affine_matrix.i:169: Error: Unknown SWIG preprocessor directive: a (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/affine_matrix.i:170: Error: Unknown SWIG preprocessor directive: as (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/hit_test.i:71: Error: Unknown SWIG preprocessor directive: Check (if this is a block of target language code, delimit it with %{ and %})
    kiva/agg/src/hit_test.i:80: Error: Unknown SWIG preprocessor directive: Check (if this is a block of target language code, delimit it with %{ and %})
    error: command 'swig' failed with exit status 1
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/lib64/python2.7/site-packages/numpy/__init__.pyc/include/python2.7 is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/local/include/python2.7 is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path  is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11R6/lib64 is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11R6/lib is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11/lib64 is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11/lib is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11R6/include is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:576: UserWarning: Specified path /usr/X11/include is invalid.

  warnings.warn('Specified path %s is invalid.' % d)

abort: there is no Mercurial repository here (.hg not found)

could not resolve pattern in 'kiva': '*.txt'

non-existing path in 'kiva/agg': 'tests'

could not resolve pattern in 'kiva/agg': '*.txt'

could not resolve pattern in 'kiva/agg': '*.bat'

could not resolve pattern in 'kiva': 'fonttools/fontTools/*.txt'

running egg_info

running build_src

build_src

building library "freetype2_src" sources

creating build

creating build/src.linux-x86_64-2.7

  adding 'kiva/agg/freetype2/src/autofit/autofit.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftbase.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftsystem.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftinit.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftglyph.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftmm.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftbdf.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftbbox.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftdebug.c' to sources.

  adding 'kiva/agg/freetype2/src/base/ftxf86.c' to sources.

  adding 'kiva/agg/freetype2/src/base/fttype1.c' to sources.

  adding 'kiva/agg/freetype2/src/bdf/bdf.c' to sources.

  adding 'kiva/agg/freetype2/src/cff/cff.c' to sources.

  adding 'kiva/agg/freetype2/src/cid/type1cid.c' to sources.

  adding 'kiva/agg/freetype2/src/lzw/ftlzw.c' to sources.

  adding 'kiva/agg/freetype2/src/pcf/pcf.c' to sources.

  adding 'kiva/agg/freetype2/src/pfr/pfr.c' to sources.

  adding 'kiva/agg/freetype2/src/psaux/psaux.c' to sources.

  adding 'kiva/agg/freetype2/src/pshinter/pshinter.c' to sources.

  adding 'kiva/agg/freetype2/src/psnames/psnames.c' to sources.

  adding 'kiva/agg/freetype2/src/raster/raster.c' to sources.

  adding 'kiva/agg/freetype2/src/sfnt/sfnt.c' to sources.

  adding 'kiva/agg/freetype2/src/smooth/smooth.c' to sources.

  adding 'kiva/agg/freetype2/src/truetype/truetype.c' to sources.

  adding 'kiva/agg/freetype2/src/type1/type1.c' to sources.

  adding 'kiva/agg/freetype2/src/type42/type42.c' to sources.

  adding 'kiva/agg/freetype2/src/winfonts/winfnt.c' to sources.

  adding 'kiva/agg/freetype2/src/gzip/ftgzip.c' to sources.

building library "agg24_src" sources

building library "kiva_src" sources

building extension "kiva.agg._agg" sources

creating build/src.linux-x86_64-2.7/kiva

creating build/src.linux-x86_64-2.7/kiva/agg

swig++: kiva/agg/agg.i

swig -python -c++ -Ikiva/agg/src -Ikiva/agg/agg-24/include -Ikiva/agg/agg-24/font_freetype -Ikiva/agg/freetype2/src/autofit -Ikiva/agg/freetype2/src/base -Ikiva/agg/freetype2/src/bdf -Ikiva/agg/freetype2/src/cache -Ikiva/agg/freetype2/src/cff -Ikiva/agg/freetype2/src/cid -Ikiva/agg/freetype2/src/gxvalid -Ikiva/agg/freetype2/src/gzip -Ikiva/agg/freetype2/src/lzw -Ikiva/agg/freetype2/src/otvalid -Ikiva/agg/freetype2/src/pcf -Ikiva/agg/freetype2/src/pfr -Ikiva/agg/freetype2/src/psaux -Ikiva/agg/freetype2/src/pshinter -Ikiva/agg/freetype2/src/psnames -Ikiva/agg/freetype2/src/raster -Ikiva/agg/freetype2/src/sfnt -Ikiva/agg/freetype2/src/smooth -Ikiva/agg/freetype2/src/tools -Ikiva/agg/freetype2/src/truetype -Ikiva/agg/freetype2/src/type1 -Ikiva/agg/freetype2/src/type42 -Ikiva/agg/freetype2/src/winfonts -Ikiva/agg/freetype2/src/gzip -Ikiva/agg/freetype2/include -Ikiva/agg/freetype2/src -I/usr/lib64/python2.7/site-packages/numpy/core/include -o build/src.linux-x86_64-2.7/kiva/agg/agg_wrap.cpp -outdir build/src.linux-x86_64-2.7/kiva/agg kiva/agg/agg.i

kiva/agg/src/constants.i:51: Error: Unknown SWIG preprocessor directive: map (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:52: Error: Unknown SWIG preprocessor directive: marker (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:53: Error: Unknown SWIG preprocessor directive: marker (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:72: Error: Unknown SWIG preprocessor directive: Map (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:73: Error: Unknown SWIG preprocessor directive: pix (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:74: Error: Unknown SWIG preprocessor directive: pix (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:94: Error: Unknown SWIG preprocessor directive: Map (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:121: Error: Unknown SWIG preprocessor directive: Map (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:122: Error: Unknown SWIG preprocessor directive: interp (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/constants.i:123: Error: Unknown SWIG preprocessor directive: interp (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/rgba.i:85: Error: Unknown SWIG preprocessor directive: Use (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/affine_matrix.i:168: Error: Unknown SWIG preprocessor directive: AffineMatrix (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/affine_matrix.i:169: Error: Unknown SWIG preprocessor directive: a (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/affine_matrix.i:170: Error: Unknown SWIG preprocessor directive: as (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/hit_test.i:71: Error: Unknown SWIG preprocessor directive: Check (if this is a block of target language code, delimit it with %{ and %})

kiva/agg/src/hit_test.i:80: Error: Unknown SWIG preprocessor directive: Check (if this is a block of target language code, delimit it with %{ and %})

error: command 'swig' failed with exit status 1

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-kDREI5/enable
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 298, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1234, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-kDREI5/enable

**Comment by jwiggins** [comment] 2015-05-05 07:03
This looks more like an Enable installation failure than a Chaco failure.

The Enable build is failing during the agg build (big surprise). Which version of swig do you have installed on your machine?

**Comment by mckatzenelson** [comment] 2015-05-05 12:23
swig.x86_64   3.0.5-6.fc21

**Comment by jwiggins** [comment] 2015-05-05 13:09
Hmmmm... Yeah, I'm not really sure what the problem is now. The enable tarball that you've downloaded contains all the `*.i` files that are needed for the swig compilation. Additionally, I was able to build without error on Ubuntu 14.10 with swig 3.0.2. I _really_ don't want to believe that a patch release of swig would break things, but it's not out of the realm of possibility.

@cournape: Does anything here catch your eye?

**Comment by jwiggins** [comment] 2015-05-05 13:30
Nevermind... I found it. This is fixed by enthought/enable#177. Nice job, SWIG...

**Closed by jwiggins** 2015-05-05 13:30 UTC

**Comment by mckatzenelson** [comment] 2015-05-05 13:37
how do i install this?  or perhaps i should ask, what do i install?

**Comment by jwiggins** [comment] 2015-05-05 13:44
In the meantime, use Canopy/conda/PythonXY/apt-get to install Enable. Long term, this will be fixed in Enable so that it works when you install using pip.

**Comment by mckatzenelson** [comment] 2015-05-05 13:52
I don't use conda  and  fedora does not use apt-get.

**Comment by jwiggins** [comment] 2015-05-05 14:49
I guess all I can recommend at this point is cloning the code from github and installing from that.

**Comment by mckatzenelson** [comment] 2015-05-05 14:52
okay, thank you.

I think I am going to give up,  i was interested in trying acoular but 
less so after the multiple fails that showed up trying to pull in the 
dependencies, and i really cannot understand why conda exists when 
matplotlib seems to already do the job and works well within the 
standard python environment.

**Comment by jonathanrocher** [comment] 2015-05-05 16:23
@mckatzenelson If you are after static plots, then matplotlib is your best friend. Chaco is the best choice I know for building plots that you can interact with in a custom way (display custom messages when hovering over your data, update data fast, connected plots that react to each other, ...), and for embedding into a standalone application (using Traits). But that extra power comes at the cost of having to write object oriented code and having to deal with C dependencies for the packages to be fast. Dependencies like enable can (rarely) have an issue, and like @jwiggins says that is why most people use a distribution (Canopy and Anaconda, both are free and come with Chaco) that does the testing and the building for you. Good luck.

**Comment by mckatzenelson** [comment] 2015-05-05 16:53
Well the present purpose is figures for a paper.  For real time or near 
real-time, there are speed-ups for matplotlib and there are other faster 
scientific graphics packages.

As for Canopy building and testing for me, the track record so far is 
not so great.
